Repository AnnaBaeTofuMom/FindPersona, pull requests merged in 2022-06, with the labels that each got.

#1 Main 스토리보드 삭제 세팅
  .gitignore
  FindPersona.xcodeproj/project.pbxproj
  FindPersona.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  FindPersona.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  FindPersona/App/AppDelegate.swift
  FindPersona/App/SceneDelegate.swift
  FindPersona/Info.plist
  FindPersona/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  FindPersona/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  FindPersona/Resources/Assets.xcassets/Contents.json
  FindPersona/Resources/Base.lproj/LaunchScreen.storyboard
  FindPersona/Resources/Info.plist
  FindPersona/View/MainViewController.swift
Labels: good first issue

#4 [PR] 컨벤션 정립 완료 및 PR 요청
  README.md
Labels: documentation

#6 [PR] 뷰 뷰모델 프로토콜 추가
  .gitignore
  FindPersona.xcodeproj/project.pbxproj
  FindPersona.xcworkspace/contents.xcworkspacedata
  FindPersona.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  FindPersona/App/SceneDelegate.swift
  FindPersona/Builder/QuestionViewBuilder.swift
  FindPersona/Builder/ViewBuilderType.swift
  FindPersona/View/MainViewController.swift
  FindPersona/View/ViewType.swift
  FindPersona/ViewModel/MainViewModel.swift
  FindPersona/ViewModel/ViewModelType.swift
  Podfile
  Podfile.lock
Labels: enhancement

#7 [PR] README에 앱 스크린샷 추가
  README.md
Labels: documentation
